os: linux
dist: trusty
sudo: required
language: cpp
cache: ccache
compiler:
  - gcc
  - clang

git:
  depth: 5

matrix:
    include:
       - compiler: clang
         # Experimental build
         env:
           - DEVELOPER_BUILD=true
           - BUILD_SERVER=true
           - BUILD_TESTS=true
       - compiler: gcc
         # Production build
         env:
           - BUILD_CLIENT=true
           - BUILD_DOCUMENTATION=true
#          - ENABLE_COVERAGE_BUILD=true

before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt562-trusty
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt56base qt56tools
  - if [ "$ENABLE_COVERAGE_BUILD" == "true" ]; then
      sudo apt-get -qq install lcov
      ;
    fi

before_script:
  - export QTDIR="/opt/qt56"
  - export PATH="$QTDIR/bin:$PATH"
  - qt56-env.sh
  - mkdir ../build; cd ../build
  - if [ "${BUILD_CLIENT}" != "true" ]; then export BUILD_CLIENT="false"; fi
  - if [ "${BUILD_DOCUMENTATION}" != "true" ]; then export BUILD_DOCUMENTATION="false"; fi
  - if [ "${BUILD_SERVER}" != "true" ]; then export BUILD_SERVER="false"; fi
  - if [ "${DEVELOPER_BUILD}" != "true" ]; then export DEVELOPER_BUILD="false"; fi
  - if [ "${ENABLE_COVERAGE_BUILD}" != "true" ]; then export ENABLE_COVERAGE_BUILD="false"; fi
  - cmake >
    -DBUILD_CLIENT=${BUILD_CLIENT}
    -DBUILD_DOCUMENTATION=${BUILD_DOCUMENTATION}
    -DBUILD_TESTS=${BUILD_TESTS}
    -DBUILD_SERVER=${BUILD_SERVER}
    -DDEVELOPER_BUILD=${DEVELOPER_BUILD}
    -DENABLE_COVERAGE_BUILD=${ENABLE_COVERAGE_BUILD}
    ../telegram-qt

script:
  - cmake --build . -- -j3 -k || travis_terminate 1
  - QT_LOGGING_RULES="telegram.*.debug=true" CTEST_OUTPUT_ON_FAILURE=1 ctest --force-new-ctest-process

after_success:
  - >
    if [ "$ENABLE_COVERAGE_BUILD" == "true" ]; then
      make coverage
      # Uploading report to CodeCov
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    fi

notifications:
  email: false
